# Generated by Django 4.0.4 on 2025-08-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='otsikko (pakollinen)')),
                ('image', models.ImageField(upload_to='slide_app', verbose_name='kuva')),
            ],
        ),
    ]
