# Generated by Django 4.0.4 on 2025-08-20 08:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import twincat_logger.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.CharField(default=twincat_logger.models.id_gen, max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20, unique=True, verbose_name='Short name')),
                ('long_name', models.CharField(max_length=255, verbose_name='Long name')),
            ],
            options={
                'verbose_name': 'Production line',
                'verbose_name_plural': 'Production lines',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=50, verbose_name='Data name')),
                ('data_field', models.FloatField(blank=True, default=None, null=True, verbose_name='Data field')),
                ('time_of_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Time of creation')),
                ('sender_ip', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Sender ip')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='twincat_logger.productionline', verbose_name='Production line')),
            ],
            options={
                'verbose_name': 'Log data',
                'verbose_name_plural': 'Log data',
                'ordering': ['time_of_creation'],
            },
        ),
    ]
