# Generated by Django 4.0.4 on 2025-08-20 10:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twincat_logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('ALERT', 'Alert'), ('ERROR', 'Error'), ('PRODUCT_REJECTION', 'Product rejection')], default=('ALERT', 'Alert'), max_length=50, verbose_name='Message type')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('time_of_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Time of creation')),
                ('sender_ip', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='Sender ip')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logmessage', to='twincat_logger.productionline', verbose_name='Production line')),
            ],
            options={
                'verbose_name': 'Log message',
                'verbose_name_plural': 'Log messages',
                'ordering': ['time_of_creation'],
            },
        ),
    ]
