# Generated by Django 4.0.4 on 2025-08-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twincat_logger', '0002_logmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmessage',
            name='message',
        ),
        migrations.AddField(
            model_name='logmessage',
            name='message_text',
            field=models.CharField(default='EMPTY', max_length=255, verbose_name='Message text'),
        ),
    ]
